### ISSUE TITLE
non-iid sample functions

### ISSUE THREAD

**Issue by weiwu99** [Hongyu-He/ece685_project#4]
Create a non-iid dataset class for federated learning

**Comment by Hongyu-He** [comment]
For the second parameters of `def sample_noniid(dataset, num_users)`, instead of using `num_users`, use `local_data_dist`, which is the distribution of each local datasets. To be more concrete:

Suppose we have 5 classes and 3 clients, `local_data_dist` is a 3 by 5 matrix, where each row represents the class distribution of each local dataset. For example, [1, 0, 0, 0, 0] means this local dataset only has class 1. [0.5, 0.5, 0, 0, 0] means this local dataset is half composed of class 1 and the other half is class 2. Obviously, the sum of each row should be 1.

**Comment by Hongyu-He** [comment]
Aslo add the third parameter: (bool): `overlap`, which means whether allow the datasets of two different clients have overlap, i.e. there exists some images that are owned by both clients (or multiple clients). 

The forth parameter: `ratio` controls how many data each clients have. `ratio = 0.2` means each client has 0.2 of the whole dataset. (if we have 10000 images in total, then each client holds 2000 images in this case). When `overlap = False`, `ratio = 1 / num_users`, where `num_users = len(local_data_dist)`.
